### ISSUE TITLE
Errors while using with PowerShell Core on Mac

### ISSUE THREAD

**Issue by genebean** [Jaykul/PowerLine#18] opened 2017-06-09 05:17 UTC
Ran into the problems below while trying this out on my Mac with the latest version of PowerShell:

```powershell
PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

cdLoading personal and system profiles took 827ms.

PS /Users/gene.liverman> $PSVersionTable.PSVersion

Major Minor Patch Label
----- ----- ----- -----
    6     0     0 beta

PS /Users/gene.liverman> Install-Module PowerLine -Scope CurrentUser

Untrusted repository 
You are installing the modules from an untrusted repository. If you trust this repository,
change its InstallationPolicy value by running the Set-PSRepository cmdlet. Are you
sure you want to install the modules from 'PSGallery'?
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "N"): y

PS /Users/gene.liverman> Get-Module -ListAvailable PowerLine


    Directory: /Users/gene.liverman/.local/share/powershell/Modules


ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     2.3.1      PowerLine                           {Set-PowerLinePrompt, Add-PowerLineBlock, New-TextFactory, Get-Elapsed...}


PS /Users/gene.liverman> using module PowerLine
Exception calling "EnableVirtualTerminalProcessing" with "0" argument(s): "The type initializer for 'PoshCode.Pansies.Console.WindowsHelper' threw an exception."
    + CategoryInfo          : InvalidOperation: (/Users/gene.liv.../PowerLine.psd1:String) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : TypeInitializationException,Microsoft.PowerShell.Commands.ImportModuleCommand

PS /Users/gene.liverman> $PowerLinePrompt = @(
>>         @{ bg = "Cyan";     fg = "White"; text = { $MyInvocation.HistoryId } }
>>         @{ bg = "DarkBlue"; fg = "White"; text = { $pwd } }
>>     )

PS /Users/gene.liverman> Set-PowerLinePrompt -PowerLineFont 
The property 'UseAnsiEscapes' cannot be found on this object. Verify that the property exists and can be set.
At /Users/gene.liverman/.local/share/powershell/Modules/PowerLine/2.3.1/PowerLine.psm1:420 char:5
+     $global:PowerLinePrompt.UseAnsiEscapes = $UseAnsiEscapes
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : PropertyAssignmentException

The property 'RestoreVirtualTerminal' cannot be found on this object. Verify that the property exists and can be set.
At /Users/gene.liverman/.local/share/powershell/Modules/PowerLine/2.3.1/PowerLine.psm1:421 char:5
+     $global:PowerLinePrompt.RestoreVirtualTerminal = $RestoreVirtualT ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : PropertyAssignmentException

PS>
```

**Comment by tylerl0706** [comment] 2018-02-26 05:26
Run into this too on macOS :(

**Comment by Jaykul** [comment] 2018-12-11 04:01
I think you just need to use an older version of PANSIES -- the pre-releases are kind-of Windows only

**Comment by ExE-Boss** [comment] 2019-09-11 22:03
There is also #52, which is caused by https://github.com/PowerShell/PowerShell/issues/10092.

**Comment by Jaykul** [comment] 2019-10-26 15:58
And apparently #44

**Comment by Jaykul** [comment] 2021-07-14 05:52
I believe **all** of these are fixed now.

Since this is all very old, I'm going to assume people are as bad as I am about noticing notifications from github, and I'm going to close it without confirming with all of the reporters. If there are more cross-platform bugs, let's open new issues ;-)

**Closed by Jaykul** 2021-07-14 05:52 UTC
Labels: 50 - External
